netaddr/netaddr

- netaddr/strategy/eui64.py
- netaddr/tests/2.x/eui/eui64.txt
- netaddr/tests/3.x/eui/eui64.txt
EUI-48 addresses can be supplied with colons or dashes as a delimiter. This PR gives the same possibility for EUI-64 addreses.
> Handle eui64 addresses with colon as a delimiter and without delimeter.

- netaddr/ip/__init__.py
I added some ranges based on the summary in RFC 6890. As closely as possible, I tried to classify them correctly as **PRIVATE** or **RESERVED**.
> IPV4 reserved & private ranges

- netaddr/ip/__init__.py
- netaddr/tests/2.x/ip/constructor.txt
Removes `__dict__` from `IPNetwork`, which also defines `__slots__`.  It was accidentally picking up a dict via the IPListMixin.
> Add __slots__ definition to IPListMixin.

- test/ip/test_ip_sets.py
Do not assume that IPSet.pop will always return the same item.  The
pop method is implemented via the popitem method on the underlying
_cidrs object, which is a dict.
dict.popitem is documented as:
Remove and return an arbitrary (key, value) pair from the dictionary.
So one cannot assert that the value popped from an IPSet will be a
specific item in the set.
Instead, assert that the item popped out of the set is present in the
other set.
> Fix bad pop() assumption in test

- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_v4.py
- netaddr/tests/ip/test_ip_v6.py
Bug fix for issue #122 
To confirm:
```
$ sipcalc 0.0.0.0/0
-[ipv4 : 0.0.0.0/0] - 0
[CIDR]
Host address		- 0.0.0.0
Host address (decimal)	- 0
Host address (hex)	- 0
Network address		- 0.0.0.0
Network mask		- 0.0.0.0
Network mask (bits)	- 0
Network mask (hex)	- 0
Broadcast address	- 255.255.255.255
Cisco wildcard		- 255.255.255.255
Addresses in network	- 4294967295
Network range		- 0.0.0.0 - 255.255.255.255
Usable range		- 0.0.0.1 - 255.255.255.254
```
and
```
$ sipcalc ::/0
-[ipv6 : ::/0] - 0
[IPV6 INFO]
Expanded Address	- 0000:0000:0000:0000:0000:0000:0000:0000
Compressed address	- ::
Subnet prefix (masked)	- 0:0:0:0:0:0:0:0/0
Address ID (masked)	- 0:0:0:0:0:0:0:0/0
Prefix address		- 0:0:0:0:0:0:0:0
Prefix length		- 0
Address type		- Reserved
Comment			- Unspecified
Network range		- …
```
> fix IPAddress().netmask_bits to return 0 for 0.0.0.0 and [::] addresses

- netaddr/ip/__init__.py
Missing implicit_prefix arg was causing unnecessary calls to
cidr_abbrev_to_verbose, when the prefix is already normalized. Was also
causing an unnecessary guess of the IP version. These make a difference
when expanding many items.
> Fix IPNetwork.subnet doing unnecessary work

- netaddr/ip/__init__.py
Raising StopIteration in generators is deprecated and will be converted to RuntimeError in Python3.7.
Instead of raising StopIteration the generator can be stopped by just a simple 'return' statement.
For details please visit https://www.python.org/dev/peps/pep-0479/
> PEP 479: 'return' instead of 'raise StopIteration'.

- netaddr/eui/__init__.py
- netaddr/ip/__init__.py
- netaddr/ip/sets.py
Previously attempting to create a weak reference to an IPAddress object
for example resulted with
cannot create weak reference to 'IPAddress' object
because if __slots__ is present it needs to contain __weakref__ in order
for weak references to work.
Fixes GH-161.
> Support weak references

- MANIFEST.in
Hi,
could you please add this folder so that PyPI tarballs contain all the necessary files to build the doc? At the moment, it results in an incomplete build:
```
/var/tmp/portage/dev-python/netaddr-0.8.0/work/netaddr-0.8.0-python3_9/lib/netaddr/ip/__init__.py:docstring of netaddr.IPAddress.__bytes__:2: WARNING: Field list ends without a blank line; unexpected unindent.
/var/tmp/portage/dev-python/netaddr-0.8.0/work/netaddr-0.8.0-python3_9/lib/netaddr/ip/nmap.py:docstring of netaddr.iter_nmap_range:6: WARNING: Inline emphasis start-string without end-string.
/var/tmp/portage/dev-python/netaddr-0.8.0/work/netaddr-0.8.0/docs/source/contributors.rst:5: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'THANKS'. …
```
> Include tutorials in source distributions

- .github/workflows/ci.yml
Not all Python versions are available on 22.04[1] and our CI is currently not working because of that.
[1] https://github.com/actions/setup-python/issues/544#issuecomment-1324999753
> Pin the Ubuntu CI runner to version 20.04

- .github/workflows/ci.yml
It's currently failing because:
* Python 2.7 is no longer supported[1]
* setup-python v2 can't find PyPy3.6 on Mac, I think upgrading to v4 will help
Upgrading setup-python to v4 requires us to change how to refer to PyPy – we have to specify the actual version now.
[1] https://github.com/actions/setup-python/issues/672
> Get the CI running again

- .github/workflows/ci.yml
When you go to [1] for example you'll see we have twice as many CI jobs compared to what we expect (36 instead of 18).
Let's only run "push" jobs on master.
[1] https://github.com/netaddr/netaddr/pull/260
> Stop running CI twice in PRs made from this repository

- README.rst
> Deprecate Python 3.6 as well

- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_v4.py
- netaddr/tests/ip/test_ip_v6.py
This is a cherry pick of commit [1] later temporarily reverted in [2] to unblock the 0.8.0 release.
The original commit message:
Like RFC 3021, IPv6 defines point-to-point subnets that must
be handled separately, i.e. don't reserve first IP address.
This patch aims to implement this, while refactoring code in
iter_host function to reduce code duplication.
Tests for this feature also added to ensure there is no regression.
Signed-off-by: Damien Claisse <d.claisse@criteo.com>
We're preparing 0.9.0 release so this can land again (for good this time).
[1] 2984c0a40a70 ("Handle RFC 6164 IPv6 addresses")
[2] 67f1992e73df ("Revert "Handle RFC 6164 IPv6 addresses"")
> Re-land: Handle RFC 6164 IPv6 addresses

- netaddr/core.py
Right now this variable is still in a module's namespace as a global one:
```python
>>> from netaddr.core import a
>>> a
42
```
Two problems:
1. We should not have these names to leak to users, because this is an internal stuff
2. External tools like `typeshed` detect this variable https://github.com/python/typeshed/blob/8597724ac113d187d2ebc9f58cef3b410b1d5dae/stubs/netaddr/%40tests/stubtest_allowlist.txt#L3 and we have to ignore from our CI checks
So, there's no clear point to keep it, but there are clear points to remove it from the global namespace of this module.
> Delete `a` temp var in `netaddr.core`

- docs/source/conf.py
- netaddr/ip/__init__.py
- netaddr/ip/nmap.py
I want to enable some strictness flags in documentation builds so that warnings are treated as errors.
When working on that I discovered a few existing warnings:
WARNING: html_static_path entry '_static' does not exist
/Users/kuba/projects/netaddr/netaddr/ip/__init__.py:docstring of netaddr.ip.IPAddress.__bytes__:2: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/kuba/projects/netaddr/netaddr/ip/nmap.py:docstring of netaddr.ip.nmap.iter_nmap_range:6: WARNING: Inline emphasis start-string without end-string.
Let's resolve them.
> Fix documentation warnings

- .readthedocs.yaml
RTD has been requiring a configuration file for a while, this change should resolve the documentation build failures[1].
[1] https://readthedocs.org/projects/netaddr/builds/22845819/
> Provide ReadTheDocs configuration

- netaddr/compat.py
- netaddr/eui/__init__.py
- netaddr/eui/ieee.py
- netaddr/ip/iana.py
- netaddr/tests/eui/test_ieee_parsers.py
importlib.resources.open_binary() has been deprecated
See:
https://docs.python.org/3.13/whatsnew/3.13.html
https://docs.python.org/3/library/importlib.resources.html#importlib.resources.open_binary
Originally reported via:
https://bugzilla.redhat.com/show_bug.cgi?id=2246093
> Improve Python 3.13 compatibility

- .readthedocs.yaml
- Makefile
- docs/requirements.txt
- docs/source/conf.py
The default one feels a bit outdated to me, let's try this[1].
I initially wanted to go with the RTD theme but it doesn't
support dark mode natively[2].
The theme is used in Python Developer's Guide[3] and it looks
nice in my opinion.
[1] https://github.com/pradyunsg/furo#elevator-pitch
[2] https://github.com/readthedocs/sphinx_rtd_theme/issues/224
[3] https://devguide.python.org/
> Change the documentation theme to Furo

- docs/source/conf.py
This is a handy switch that should allow us avoiding adding invalid references to the documentation.
> Make Sphinx reject invalid references

- pyproject.toml
- pytest.ini
This includes doctests found in the docstrings in the code and doctests from the .rst files.
We currently don't have either in the code but I intend to add some and I'd like this piece of infrastructure in place first.
> Make pytest run doctests

- .gitignore
Seems like it's been missing from our .gitignore.
> Ignore the .coverage test artifact

- docs/poetry.lock
- docs/pyproject.toml
I find it useful for working on the documentation.
Setup:
cd docs
poetry install --with=autobuild
Use:
PYTHONPATH=.. poetry run sphinx-autobuild source build/html --watch ../netaddr
> Add sphinx-autobuild as an optional docs dependency

- docs/source/api.rst
- docs/source/conf.py
I don't imagine they're terribly useful and I believe they create more issues than they actually solve.
I expect no user is gonna care that __iadd__ is implemented and what it means, they're probably gonna be more interested in the fact that you can do
ip = IPAddress('10.0.0.1')
ip += 1
I think Python's ipaddress documentation does it right as it lists various conversion options and operator use[1], we should probably get something like that in place.
One exception is we still want to show the constructors so some configuration added + custom exclusion options for exceptions, otherwise the documentation would show the dummy __init__(*args, **kwargs) constructors for them which doesn't help anyone.
[1] https://docs.python.org/3/library/ipaddress.html#conversion-to-strings-and-integers
> Hide non-constructor dunder methods from the documentation

- docs/source/api.rst
- netaddr/eui/__init__.py
- netaddr/ip/__init__.py
Seems like a good thing to have in the documentation and it's simple enough to add.
> Link to formatting dialects instead of only mentioning them

- docs/source/api.rst
These all (is_ipv4_mapped(), is_link_local() etc.) are a valuable and important part of IPAddress' public interface.
> Show BaseIP-inherited properties in IPAddress' documentation

- netaddr/ip/__init__.py
This is one of the pieces missing to have a good IPv4-mapped IPv6 address handling story.
Following Rust's IpAddr::to_canonical() design[1][2][3] which seems sensible to me (except that ours is simpler as we don't have separate types for IPv4 and IPv6 addresses – yet).
Also, relying on doctests[4] to test this feature – no need to make things more difficult than they need to be.
[1] https://doc.rust-lang.org/std/net/enum.IpAddr.html#method.to_canonical
[2] https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#method.to_canonical
[3] https://github.com/rust-lang/rust/pull/87708
[4] 3290b50baa64 ("Make pytest run doctests (#280)")
> Implement IPAddress.to_canonical()

- docs/source/how-to.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/reference.rst
- docs/source/tutorials.rst
I've been big fan of the Diataxis documentation framework, both as a documentation reader and a writer.
Some of the content we have doesn't necessarily fit one of the modes *perfectly* but that's fine, it's a start.
Notable I left the Introduction section outside of the modes (I intend to remove it altogether) and the Authors and Contributors sections I'm not sure what to do about.
I also changed one document's title so that it fits the format expected by the How-to guides (How to ...).
[1] https://diataxis.fr/
> Reorganize the documentation

- docs/source/conf.py
- docs/source/static/custom.css
I sometimes find it useful to see if a link takes me to "the outside" or if I'm still gonna be in the documentation when I click it.
The style snippet taken almost verbatim from [1].
[1] https://github.com/pradyunsg/furo/discussions/348#discussioncomment-1931019
> Style external links in the documentation

- docs/source/dev-how-to/index.rst
- docs/source/dev-how-to/release.rst
- docs/source/index.rst
Less noise in the working directory, more structure to the documentation.
Changed the title to fit the "How to ..." format.
> Make the release process instructions part of the documentation

- CHANGELOG
- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip.py
Ignoring invalid flags is likely to lead to hard to debug issues, better reject them right away.
> Protect against constructing objects with invalid flags

- CHANGELOG
- netaddr/ip/__init__.py
Following a TODO from parse_ip_network():
if implicit_prefix:
#TODO: deprecate this option in netaddr 0.8.x
addr = cidr_abbrev_to_verbose(addr)
Seems good to get rid of this, can potentially lead to ambiguous outcomes.
> Deprecate the support for abbreviated CIDR format

- netaddr/tests/ip/test_ip_categories.py
There was quite a bit of repetition there and for the addresses we have in the test code we were only verifying some of their is_*() values.
Considering I want to add some new is_*() methods I figured I'd refactor the code first so that the test suite is more robust and it's easier to discover invalid assumptions or other mistakes.
I got the refactoring idea after reading the Rust core library tests for a similar feature[1].
The addresses we test are the same as before, just reordered.
There are some... interesting category assignments that this change surfaced, we could probably revisit some of them.
[1] https://github.com/rust-lang/rust/blob/767453eb7ca188e991ac5568c17b984dd4893e77/library/core/tests/net/ip_addr.rs#L475C12-L475C12
> Refactor IP category tests

- CHANGELOG
- docs/source/api.rst
- netaddr/__init__.py
- netaddr/core.py
- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip.py
- netaddr/tests/ip/test_ip_v4.py
I want to make the default parsing more restrictive (separate PRs)
and this is needed as an escape hatch for people who need the old
behavior.
No actual behavior changes yet, just preparations.
> Add a way to request legacy IPv4 parsing from IPAddress

- CHANGELOG
- docs/source/api.rst
- netaddr/__init__.py
- netaddr/core.py
- netaddr/ip/__init__.py
- netaddr/strategy/ipv4.py
- netaddr/tests/ip/test_ip.py
- netaddr/tests/ip/test_ip_v4.py
It's like INET_PTON but it predictably, on all operating systems, rejects leading zeros.
The intention is to make it the default in the next major release (after deprecating the current behavior, which will be implemented separately).
> Introduce the INET_PTON_STRICT IPv4 parsing mode

- CHANGELOG
- docs/source/api.rst
- netaddr/__init__.py
- netaddr/core.py
- netaddr/ip/__init__.py
- netaddr/strategy/ipv4.py
- netaddr/tests/ip/test_ip.py
- netaddr/tests/ip/test_ip_v4.py
The original idea was to have a new IPv4 parsing mode as INET_PTON permits leading zeros on some platforms (at least Mac from what I saw).
I just realized it's probably a much better idea to make INET_PTON always reject leading zeros unless combined with ZEROFILL.
In line with the above let's revert the INET_PTON_STRICT addition.
This reverts commit 77919df89dbafe0c65acdd1b0ec22aaba3a54967.
> Revert "Introduce the INET_PTON_STRICT IPv4 parsing mode (#311)"

- CHANGELOG
- docs/source/api.rst
- netaddr/ip/__init__.py
Give the users heads up about some things that are about to change.
This is all to make the library more difficult to misuse, the legacy IPv4 parsing is pretty error prone and I'd expect it to not be widely used.
> Document some deprecations

- CHANGELOG
- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_categories.py
I plan to deprecate the existing is_private method and we neeed some
better replacements for it. This is one, there'll be more to complement
it.
"ipv4" in the name to make it clear it's IPv4-only.
> Add IPAddress.is_ipv4_private_use

- CHANGELOG
- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_categories.py
I plan to deprecate the is_private methods and this will serve as a partial replacement for IPv6 addresses.
> Implement IPAddress.is_ipv6_unique_local

- CHANGELOG
- netaddr/ip/__init__.py
It's been using non-standard terminology and mixing multiple separate concepts together, I think it's better to replace it with more precise or otherwise more predictable handling.
> Deprecate IPAddress.is_private

- CHANGELOG
They're quite opaque and if someone truly needs them I think their code will benefit from the extra verbosity.
> Deprecate the one-letter flags

- netaddr/ip/nmap.py
We've had an invalid escape sequence here:
/Users/user/projects/netaddr/netaddr/ip/nmap.py:105: SyntaxWarning: invalid escape sequence '\*'
"""
<unknown>:105: SyntaxWarning: invalid escape sequence '\*'
> Get rid of a SyntaxWarning

- CHANGELOG
A counterpart to recently added [1].
[1] 8e9a2820dde4 ("Make it clear what's public API and what isn't (#326)")
> Mention imports from subpackages in the changelog

- netaddr/ip/sets.py
- netaddr/strategy/ipv4.py
End-users are supposed to import things from the top level netaddr namespace, not from the submodules.
> Remove some private API references from the documentation

- Makefile
PyPI doesn't accept multiple source distributions (anymore?), let's stick to one.
> Produce only one source distribution

- Makefile
We don't upload the documentation manually anywhere anyway, ReadTheDocs picks it up directly from GitHub.
> Stop (re)building the documentation in "make dist"

- CHANGELOG
- netaddr/strategy/ipv4.py
I forgot about this function when I applied [1].
[1] 86f1e3d95618 ("Document some deprecations (#320)")
> Mention a valid_ipv4-related deprecation

- netaddr/ip/nmap.py
Apparently the leading asterisk prevents the parameter from being included in docstring tooltips in IntelliJ IDEA.
> Make iter_nmap_range's docstring render correctly in IntelliJ IDEA

- netaddr/compat.py
- setup.py
We only support Python 3.7+ now and it's built in.
> Stop depending on importlib_resources

- netaddr/strategy/eui48.py
- netaddr/strategy/eui64.py
This makes sure this constant only ever has one type, which is something that will be important once I start running Mypy as part of CI.
> Compile the regular expressions right away

- netaddr/tests/eui/test_eui.py
- netaddr/tests/eui/test_ieee_parsers.py
- netaddr/tests/ip/test_ip_v4.py
- netaddr/tests/ip/test_ip_v6.py
- netaddr/tests/strategy/test_eui48_strategy.py
- netaddr/tests/strategy/test_ipv4_strategy.py
- netaddr/tests/strategy/test_ipv6_strategy.py
No longer necessary or relevant, Python 2 support has been dropped.
> Remove some Python 2-related artifacts

- tutorials/2.x/eui/tutorial.txt
- tutorials/2.x/ip/tutorial.txt
The code had to be made Python 3-compatible and contain up to date information.
There was an assignment missing too.
One piece of doctest has non-deterministic results so that had to be handled with ellipsis.
> Prepare the tutorials for doctest running

- CHANGELOG
- netaddr/strategy/ipv4.py
- netaddr/tests/ip/test_ip_v4.py
- netaddr/tests/ip/test_platform_osx.py
Deprecated a while ago as source of potential tricky problems.
> Reject IPv4 leading zeros in INET_PTON parsing mode

- docs/source/api.rst
Forgot to do it in [1].
[1] 3644adaa7599 ("Reject IPv4 leading zeros in INET_PTON parsing mode (#356)")
> Fix INET_PTON's behavior change documentation

- CHANGELOG
- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_v4.py
As planned before, I don't think this feature deserves first-class support in IPNetwork.
> Drop implicit_prefix support in IPNetwork

- CHANGELOG
- netaddr/strategy/ipv4.py
- netaddr/tests/strategy/test_ipv4_strategy.py
I applied two changes recently that made ipv4.str_to_int/IPAddress stricter[1][2], it only make sense that valid_str matches that new semantics.
It's achieved with better code reuse, which is (almost) always welcome.
[1] 95bd1f46109e ("Make IPv4 parsing more restrictive by default (#359)")
[2] 3644adaa7599 ("Reject IPv4 leading zeros in INET_PTON parsing mode (#356)")
> Make ipv4.valid_str (AKA valid_ipv6) match IPAddress strictness

- CHANGELOG
- netaddr/eui/__init__.py
- netaddr/tests/eui/test_eui.py
It was simply ignored before.
Fixes: https://github.com/netaddr/netaddr/issues/250
> Fix dialect handling in EUI during copy-construction

- pyproject.toml
These links will be visible on the package's PyPI page:
> ![image](https://github.com/netaddr/netaddr/assets/137616/76b548ce-5af6-4ad1-9aa6-f44b4a2cacbb)
And also tools like Renovate bot use this to provide direct access to the changelog for a dependency update.
> Add changelog URL to package metadata

- netaddr/fbsocket.py
- netaddr/tests/ip/test_socket_module_fallback.py
The original socket.inet_pton raises TypeError on non-str passed as an address and OSError in case of an invalid address.
This will help with more precise exception handling (we use socket.inet_pton and fbsocket.inet_pton interchangeably in a couple of places).
> Improve the exceptions raised by fbsocket's inet_pton

- .github/workflows/ci.yml
It seems that there's no longer Python 3.7 available for the test runs in CI[1]:
Run actions/setup-python@v5
Installed versions
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.4.1.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
This change is not dropping support for Python 3.7 yet, we just can't test with it anymore using GH Actions.
[1] https://github.com/netaddr/netaddr/actions/runs/9165981748/job/25200497622
> Drop Python 3.7 from CI

- netaddr/strategy/ipv4.py
- netaddr/tests/ip/test_ip_v6.py
- netaddr/tests/strategy/test_ipv4_strategy.py
It was a regression, affected IPAddress.
Fixes: d39b7d124280 ("Handle IP parsing errors more precisely")
Resolves: https://github.com/netaddr/netaddr/issues/383
> Fix IPv6 parsing with ZEROFILL enabled

- netaddr/ip/__init__.py
- netaddr/tests/ip/test_ip_v4.py
This introduces the new expand argument to IPNetwork class, so that users can retain the previous behavior of netaddr < 1.0.0 optionally.
```
>>> import netaddr
>>> netaddr.IPNetwork('10/8')
Traceback (most recent call last):
File "/home/tkajinam/git/python/netaddr/netaddr/strategy/ipv4.py", line 126, in str_to_int
packed = _inet_pton(AF_INET, addr)
^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: illegal IP address string passed to inet_pton
...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/tkajinam/git/python/netaddr/netaddr/ip/__init__.py", line 1035, in __init__
raise AddrFormatError('invalid IPNetwork %s' % (addr,))
netaddr.core.AddrFormatError: invalid IPNetwork 10/8
>>> …
```
> IPNetwork: Allow partial addresses (again)

- .github/workflows/ci.yml
We support Python 3.12, better test with it too.
> Include Python 3.12 in the CI configuration
